sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 8
  - 'stable'

env:
  global:
    COVERALLS_PARALLEL: true

before_install:
  - npm cache clear --force
  - npm i npm@latest -g

after_success: nyc report --reporter=text-lcov | coveralls
