environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true

matrix:
  fast_finish: true

build: off
version: '{build}'
test_script:
  - node --version
  - npm test
