environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm cache clear
  - npm i npm@latest -g
  - appveyor-retry npm install

matrix:
  fast_finish: true

build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm test
