version: '{build}'

clone_depth: 10

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 5 npm -g install npm@4
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: true
